[tox]
envlist =
  lint
  py39

[testenv]
description = Run the unit tests
deps =
    -rtest-requirements.txt
    -rdev-requirements.txt
commands =
    {envpython} -m pytest {posargs: -vv } tests

[testenv:lint]
description = Performs linting tasks
deps =
    flake8
commands = python -m flake8 {posargs}

[flake8]
; flake8 options: https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-max-line-length
max-line-length = 100
exclude =
    # No need to traverse our git directory
    .git,
    # There's no value in checking cache directories
    __pycache__
    # no need to traverse .tox
    .tox
    .pytest*
    .eggs
    venv

